# Generated by Django 5.1.6 on 2025-02-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Store Name",
                "verbose_name_plural": "Store Names",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="sellerprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Seller Profile",
                "verbose_name_plural": "Seller Profiles",
            },
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="store_name",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller_profile",
                to="shop.storename",
            ),
        ),
    ]
