# Generated by Django 5.1.6 on 2025-02-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_photo_user_photo_alter_product_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brand_logos/"),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("gray", "Gray"),
                    ("brown", "Brown"),
                    ("pink", "Pink"),
                    ("purple", "Purple"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cotton", "Cotton"),
                    ("leather", "Leather"),
                    ("wood", "Wood"),
                    ("metal", "Metal"),
                    ("plastic", "Plastic"),
                    ("glass", "Glass"),
                    ("silk", "Silk"),
                    ("wool", "Wool"),
                    ("linen", "Linen"),
                    ("ceramic", "Ceramic"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.category",
            ),
        ),
    ]
