# Generated by Django 5.1.6 on 2025-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_discount_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="storename",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a store logos.",
                null=True,
                upload_to="store_logos/",
            ),
        ),
    ]
