# Generated by Django 5.1.6 on 2025-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_storename_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
